<<<<<<< HEAD
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
=======
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
>>>>>>> 0b11e4e175a96f18405a55b929cb0d2f7a81cdf7

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
<<<<<<< HEAD
    url: env("DATABASE_URL"),
  },
});
=======
    url: process.env["DATABASE_URL"],
  },
});
>>>>>>> 0b11e4e175a96f18405a55b929cb0d2f7a81cdf7
